app:
  build: .
  dockerfile: Dockerfile.ci
  volumes:
    - ./:/app
    - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent
  environment:
    - BUILDKITE_AGENT_ACCESS_TOKEN
    - BUILDKITE_JOB_ID
    - BUILDKITE_BUILD_ID
    - BUILDKITE_BUILD_NUMBER
